vim.opt.hlsearch = true
vim.opt.number = true
vim.opt.autoindent = true

vim.opt.background = 'dark'

vim.api.nvim_set_keymap('i', '<C-m>sl', '\\subset', { noremap = true, silent = true })



vim.keymap.set('i', '@math', function()
	if vim.b.math == true then
		print('exit math mode')
		vim.b.math = false
		vim.keymap.del('i', 'lg')
		vim.keymap.del('i', 'sf')
		vim.keymap.del('i', 'sk')
		vim.keymap.del('i', 'sj')
		vim.keymap.del('i', 'sh')
		vim.keymap.del('i', 'sl')
		vim.keymap.del('i', 'kk')
		vim.keymap.del('i', 'jj')
		vim.keymap.del('i', 'fr')
		
		vim.keymap.del('i','@.')
		vim.keymap.del('i','@8')
		vim.keymap.del('i','@6')
		vim.keymap.del('i','@/')
		vim.keymap.del('i','@%')
		vim.keymap.del('i','@^')
		vim.keymap.del('i','@_')
		vim.keymap.del('i','@@')
		vim.keymap.del('i','@0')
		vim.keymap.del('i','@;')
		vim.keymap.del('i','@:')
		vim.keymap.del('i','@=')
		vim.keymap.del('i','@*')
		vim.keymap.del('i','@<')
		vim.keymap.del('i','@>')
		vim.keymap.del('i','@2')
		vim.keymap.del('i','@I')
		vim.keymap.del('i','@|')
		vim.keymap.del('i','@+')
		vim.keymap.del('i','@-')
		vim.keymap.del('i','@,')
		vim.keymap.del('i','@a')
		vim.keymap.del('i','@b')
		vim.keymap.del('i','@c')
		vim.keymap.del('i','@d')
		vim.keymap.del('i','@e')
		vim.keymap.del('i','@ve')
		vim.keymap.del('i','@f')
		vim.keymap.del('i','@vf')
		vim.keymap.del('i','@g')
		vim.keymap.del('i','@h')
		vim.keymap.del('i','@i')
		vim.keymap.del('i','@k')
		vim.keymap.del('i','@l')
		vim.keymap.del('i','@m')
		vim.keymap.del('i','@n')
		vim.keymap.del('i','@p')
		vim.keymap.del('i','@vp')
		vim.keymap.del('i','@q')
		vim.keymap.del('i','@vq')
		vim.keymap.del('i','@r')
		vim.keymap.del('i','@vr')
		vim.keymap.del('i','@s')
		vim.keymap.del('i','@vs')
		vim.keymap.del('i','@t')
		vim.keymap.del('i','@u')
		vim.keymap.del('i','@o')
		vim.keymap.del('i','@&')
		vim.keymap.del('i','@x')
		vim.keymap.del('i','@y')
		vim.keymap.del('i','@z')
		vim.keymap.del('i','@D')
		vim.keymap.del('i','@F')
		vim.keymap.del('i','@G')
		vim.keymap.del('i','@Q')
		vim.keymap.del('i','@L')
		vim.keymap.del('i','@P')
		vim.keymap.del('i','@X')
		vim.keymap.del('i','@Y')
		vim.keymap.del('i','@S')
		vim.keymap.del('i','@U')
		vim.keymap.del('i','@W')
		vim.keymap.del('i','@(')
		vim.keymap.del('i','@{')
		vim.keymap.del('i','@[')

	else
		print('enter math mode')
		vim.b.math = true
		vim.keymap.set('i', 'lg', '\\mathfrak{', { silent = true })
		vim.keymap.set('i', 'sf', '\\longrightarrow', { silent = true })
		vim.keymap.set('i', 'sk', '\\cup', { silent = true })
		vim.keymap.set('i', 'sj', '\\cap', { silent = true })
		vim.keymap.set('i', 'sh', '\\subset', { silent = true })
		vim.keymap.set('i', 'sl', '\\supset', { silent = true })
		vim.keymap.set('i', 'kk', '^{', { silent = true })
		vim.keymap.set('i', 'jj', '_{', { silent = true })
		vim.keymap.set('i', 'fr', '\\frac{', { silent = true })

		vim.keymap.set('i','@.', '\\cdot',{silent = true})
		vim.keymap.set('i','@8', '\\infty',{silent = true})
		vim.keymap.set('i','@6', '\\partial',{silent = true})
		vim.keymap.set('i','@/', '\\frac{$1}{$2}$0',{silent = true})
		vim.keymap.set('i','@%', '\\frac{$1}{$2}$0',{silent = true})
		vim.keymap.set('i','@^', '\\hat{${1:${TM_SELECTED_TEXT}}}$0',{silent = true})
		vim.keymap.set('i','@_', '\\bar{${1:${TM_SELECTED_TEXT}}}$0',{silent = true})
		vim.keymap.set('i','@@', '\\circ',{silent = true})
		vim.keymap.set('i','@0', '^\\circ',{silent = true})
		vim.keymap.set('i','@;', '\\dot{${1:${TM_SELECTED_TEXT}}}$0',{silent = true})
		vim.keymap.set('i','@:', '\\ddot{${1:${TM_SELECTED_TEXT}}}$0',{silent = true})
		vim.keymap.set('i','@=', '\\equiv',{silent = true})
		vim.keymap.set('i','@*', '\\times',{silent = true})
		vim.keymap.set('i','@<', '\\leq',{silent = true})
		vim.keymap.set('i','@>', '\\geq',{silent = true})
		vim.keymap.set('i','@2', '\\sqrt{${1:${TM_SELECTED_TEXT}}}$0',{silent = true})
		vim.keymap.set('i','@I', '\\int_{$1}^{$2}$0',{silent = true})
		vim.keymap.set('i','@|', '\\Big|',{silent = true})
		vim.keymap.set('i','@+', '\\bigcup',{silent = true})
		vim.keymap.set('i','@-', '\\bigcap',{silent = true})
		vim.keymap.set('i','@,', '\\nonumber',{silent = true})
		vim.keymap.set('i','@a', '\\alpha',{silent = true})
		vim.keymap.set('i','@b', '\\beta',{silent = true})
		vim.keymap.set('i','@c', '\\chi',{silent = true})
		vim.keymap.set('i','@d', '\\delta',{silent = true})
		vim.keymap.set('i','@e', '\\epsilon',{silent = true})
		vim.keymap.set('i','@ve', '\\varepsilon',{silent = true})
		vim.keymap.set('i','@f', '\\phi',{silent = true})
		vim.keymap.set('i','@vf', '\\varphi',{silent = true})
		vim.keymap.set('i','@g', '\\gamma',{silent = true})
		vim.keymap.set('i','@h', '\\eta',{silent = true})
		vim.keymap.set('i','@i', '\\iota',{silent = true})
		vim.keymap.set('i','@k', '\\kappa',{silent = true})
		vim.keymap.set('i','@l', '\\lambda',{silent = true})
		vim.keymap.set('i','@m', '\\mu',{silent = true})
		vim.keymap.set('i','@n', '\\nu',{silent = true})
		vim.keymap.set('i','@p', '\\pi',{silent = true})
		vim.keymap.set('i','@vp', '\\varpi',{silent = true})
		vim.keymap.set('i','@q', '\\theta',{silent = true})
		vim.keymap.set('i','@vq', '\\vartheta',{silent = true})
		vim.keymap.set('i','@r', '\\rho',{silent = true})
		vim.keymap.set('i','@vr', '\\varrho',{silent = true})
		vim.keymap.set('i','@s', '\\sigma',{silent = true})
		vim.keymap.set('i','@vs', '\\varsigma',{silent = true})
		vim.keymap.set('i','@t', '\\tau',{silent = true})
		vim.keymap.set('i','@u', '\\upsilon',{silent = true})
		vim.keymap.set('i','@o', '\\omega',{silent = true})
		vim.keymap.set('i','@&', '\\wedge',{silent = true})
		vim.keymap.set('i','@x', '\\xi',{silent = true})
		vim.keymap.set('i','@y', '\\psi',{silent = true})
		vim.keymap.set('i','@z', '\\zeta',{silent = true})
		vim.keymap.set('i','@D', '\\Delta',{silent = true})
		vim.keymap.set('i','@F', '\\Phi',{silent = true})
		vim.keymap.set('i','@G', '\\Gamma',{silent = true})
		vim.keymap.set('i','@Q', '\\Theta',{silent = true})
		vim.keymap.set('i','@L', '\\Lambda',{silent = true})
		vim.keymap.set('i','@P', '\\Pi',{silent = true})
		vim.keymap.set('i','@X', '\\Xi',{silent = true})
		vim.keymap.set('i','@Y', '\\Psi',{silent = true})
		vim.keymap.set('i','@S', '\\Sigma',{silent = true})
		vim.keymap.set('i','@U', '\\Upsilon',{silent = true})
		vim.keymap.set('i','@W', '\\Omega',{silent = true})
		vim.keymap.set('i','@(', '\\left( ${1:${TM_SELECTED_TEXT}} \\right)',{silent = true})
		vim.keymap.set('i','@{', '\\left\\{ ${1:${TM_SELECTED_TEXT}} \\right\\\\}',{silent = true})
		vim.keymap.set('i','@[', '\\left[ ${1:${TM_SELECTED_TEXT}} \\right]',{silent = true})
	end
end,{expr = true})


